###
GET http://localhost:8000/leaderboard

###
GET http://localhost:8000/current_games

###
POST http://localhost:8000/create_session

###
POST http://localhost:8000/play
Content-Type: application/json

{
		"session_id":1,
		"player_name":"andrey",
		"choice":"rock"
}

###
POST http://localhost:8000/play
Content-Type: application/json

{
		"session_id":1,
		"player_name":"kirill",
		"choice":"paper"
}

###
POST http://localhost:8000/play
Content-Type: application/json

{
		"session_id":1,
		"player_name":"andrey",
		"choice":"rock"
}


###
POST http://localhost:8000/join_session
Content-Type: application/json

{
		"session_id":4,
		"player_name":"kirill"
}


###
POST http://localhost:8000/join_session
Content-Type: application/json

{
		"session_id":2,
		"player_name":"andrey"
}