definitions:
  main.PlayResponse:
    properties:
      game_result:
        example: Win 1 player
        type: string
    type: object
  main.Player:
    properties:
      choice:
        type: string
      name:
        type: string
    type: object
  main.Scores:
    type: object
  main.Session:
    properties:
      id:
        type: integer
      players:
        items:
          $ref: '#/definitions/main.Player'
        type: array
      round:
        type: integer
      score:
        $ref: '#/definitions/main.Scores'
    type: object
  main.SuccessResponse:
    properties:
      session_id:
        type: integer
    type: object
host: localhost:8000
info:
  contact: {}
  title: WhoManages API
  version: "1.0"
paths:
  /create_session:
    post:
      description: Создание новой игровой сессии
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: Successful response with session ID
          schema:
            $ref: '#/definitions/main.SuccessResponse'
      summary: Создание игровой сессии
      tags:
      - Session
  /current_games:
    get:
      description: Возвращает список текущих игровых сессий, включая информацию о
        каждой сессии.
      produces:
      - application/json
      responses:
        "200":
          description: Массив сессий
          schema:
            items:
              $ref: '#/definitions/main.Session'
            type: array
      summary: Получить список текущих игровых сессий
      tags:
      - Session
  /join_session:
    post:
      description: Присоединение к игровой сессии
      parameters:
      - description: ID игровой сессии
        in: path
        name: session_id
        required: true
        type: integer
      - description: Имя игрока
        in: path
        name: player_name
        required: true
        type: string
      produces:
      - aplication/json
      responses:
        "200":
          description: Игрок успешно присоединился к сессии
          schema:
            $ref: '#/definitions/main.SuccessResponse'
      summary: Присоединение к игровой сессии
      tags:
      - Session
  /leaderboard:
    get:
      description: Возвращает рейтинг игроков в текущих игровых сессиях.
      produces:
      - application/json
      responses:
        "200":
          description: map[имя_игрока:количество_побед]
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Получить текущий рейтинг игроков
      tags:
      - Session
  /play:
    post:
      description: Производит игровой ход в рамках сессии, включая выбор игрока и
        определение победителя в раунде.
      parameters:
      - description: Идентификатор игровой сессии
        in: path
        name: session_id
        required: true
        type: integer
      - description: Имя игрока
        in: path
        name: player_name
        required: true
        type: string
      - description: Выбор игрока (rock, paper, scissors)
        in: path
        name: choice
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Результат игры
          schema:
            $ref: '#/definitions/main.PlayResponse'
      summary: Играть в рок-ножницы-бумага
      tags:
      - Session
swagger: "2.0"
